### ISSUE TITLE
Mqtt not allow Mac address as username

### ISSUE THREAD

**Issue by Ostepanov** [bytespider/Meross#32]
Hello.
Right now it's impossible to use meross devices with mqtt broker, because mqtt does not allow ":" symbol in usernames, and meross devices uses their mac address as username

https://mosquitto.org/man/mosquitto_passwd-1.html

**Comment by bytespider** [comment]
This is true of vanilla Mosquito, however there is a plugin which allows you to use other forms and database backings that do not have this limitation.

For a while Home Assistant also didn't have a problem, however since 6.0.0 https://github.com/home-assistant/addons/issues/2014 it has been nonfunctional also.
