### ISSUE TITLE
NTP queries from Meross Plugs

### ISSUE THREAD

**Issue by onewheeler70** [bytespider/Meross#79]
I have successfully set up several meross plugs using your tool and instructions. Thanks for your efforts on this. I have blocked my meross devices from accessing the internet. I have Pi-hole running on the network. The result is that the Plugs ping pihole every few seconds for a long list of DNS domain names. The Meross plug will never be able to get to those name servers, so they sit in a loop constantly querying the Pihole server. Is there any way to configure this in the meross plugs so that they ping a local network time server instead? Thanks.

**Comment by onewheeler70** [comment]
I have managed to fix this particular issue and will document here in case it is useful for others. I installed the following in a docker container on a Linux box that I have running 24/7 on my network:

https://github.com/cturra/docker-ntp

And then put in a Local DNS entry in Pihole to point pool.ntp.org to the IP address of the device running that docker container. The Meross plugs could get the time from that address, and are now quiet, reducing 3/4 of the requests to my Pihole instance.

**Comment by lupusbytes** [comment]
If others like me happens to stumble across this issue i would like to suggest an alternative to @onewheeler70 's solution.

My issue was that I use a VLAN for IoT, without internet access and my Meross WiFi LED strips wouldn't accept DHCP Option 42 to use my local NTP server.
Inspired by @onewheeler70, I put in a `RegEx filter` in my Pi-hole, so that devices in my IoT group would receive a custom reply (my local server) when querying `pool.ntp.org`, while leaving normal devices unaffected.

<img width="1106" height="176" alt="Image" src="https://github.com/user-attachments/assets/764c2855-6338-4958-b7b4-65a21cc27439" />

**Comment by lechercheur123** [comment]
Hello,
On my side, I just put a NAT rule for UDP/123 on my router for my IoT VLAN, changing the destination IPv4 address to my NTP server. Quite easy to do on a Mikrotik router (but maybe not on a consumer router)
